# Pandas

In [1]:
import pandas as pd

In [3]:
my_data=[4,5,6]

arr=pd.array(my_data) # creating an array using pandas

In [4]:
type(arr)

pandas.core.arrays.integer.IntegerArray

In [5]:
arr

<IntegerArray>
[4, 5, 6]
Length: 3, dtype: Int64

In [7]:
pd.Series(data=my_data) # creating a series using pandas

0    4
1    5
2    6
dtype: int64

In [14]:
my_data=(4,5,6)

In [15]:
labels={"a",'c','b'}

In [16]:
pd.Series(data=my_data, index=labels)

c    4
a    5
b    6
dtype: int64

In [10]:
pd.Series(arr,labels) # we can use already existing array for creating a series

a    4
b    5
c    6
dtype: Int64

In [17]:
d= {"k1":4,"k2":5,"k3":6}
d

{'k1': 4, 'k2': 5, 'k3': 6}

In [18]:
labels=['a','k2','k1']

In [21]:
pd.Series(d) # converting dictionary to series

k1    4
k2    5
k3    6
dtype: int64

In [23]:
sr1=pd.Series([1,1,3,4],["Baku","Sheki","Ganja","Sumgait"])
sr1

Baku       1
Sheki      1
Ganja      3
Sumgait    4
dtype: int64

In [24]:
sr2=pd.Series([1,2,5,1],["Sheki","Shamakhi","Sumgait","Baku"])
sr2

Sheki       1
Shamakhi    2
Sumgait     5
Baku        1
dtype: int64

In [25]:
sr3 =sr1+sr2
sr3

Baku        2.0
Ganja       NaN
Shamakhi    NaN
Sheki       2.0
Sumgait     9.0
dtype: float64

In [26]:
sr3.value_counts()

2.0    2
9.0    1
dtype: int64

In [28]:
list1 = [1,2,3,4,5,2,10,2,4,20,18,29,39,33,12]
df1 = pd.DataFrame(data=list1) #converting list to dataframe

In [29]:
df1

     0
0    1
1    2
2    3
3    4
4    5
5    2
6   10
7    2
8    4
9   20
10  18
11  29
12  39
13  33
14  12

In [ ]:
dictionary={
  "brand": "Mersedes",
  "model": "E240",
  "year": 200
}

In [31]:
df2= pd.DataFrame(list(dictionary)) # first converting dictionary to list then list to df

In [32]:
df2

       0
0  brand
1  model
2   year

In [41]:
df2_1 = pd.DataFrame(pd.Series(dictionary))
df2_1

              0
brand  Mersedes
model      E240
year       2008

In [33]:
series = pd.Series(dictionary) # directly converting dictionary to series
series

brand    Mersedes
model        E240
year         2008
dtype: object

In [34]:
series.value_counts(dropna=True) # counts the values

2008        1
Mersedes    1
E240        1
dtype: int64

In [160]:
series

brand    Mersedes
model          ML
year         2008
dtype: object

In [22]:
from numpy.random import randn
import numpy as np

In [23]:
np.random.seed(101)

In [27]:
randn(5,4)

array([[ 0.38603031,  2.08401853, -0.37651868,  0.23033634],
       [ 0.68120929,  1.03512507, -0.03116048,  1.93993231],
       [-1.00518692, -0.7417897 ,  0.18712452, -0.73284515],
       [-1.3829201 ,  1.4824955 ,  0.96145816, -2.14121229],
       [ 0.99257345,  1.19224064, -1.04677954,  1.29276458]])

In [43]:
df=pd.DataFrame(randn(5,4), ["A","B","C","D","E"], ["W","X","Y","Z"])

In [44]:
df

          W         X         Y         Z
A  0.586847 -1.621348  0.677535  0.026105
B -1.678284  0.333973 -0.532471  2.117727
C  0.197524  2.302987  0.729024 -0.863091
D  0.305632  0.243178  0.864165 -1.560931
E -0.251897 -0.578120  0.236996  0.200780

# Selection and Indexing

In [45]:
df["X"]

A   -1.621348
B    0.333973
C    2.302987
D    0.243178
E   -0.578120
Name: X, dtype: float64

In [46]:
df["New"]=df["W"]+df["Y"]

In [47]:
df[["W"]+["Y"]]

          W         Y
A  0.586847  0.677535
B -1.678284 -0.532471
C  0.197524  0.729024
D  0.305632  0.864165
E -0.251897  0.236996

In [48]:
df

          W         X         Y         Z       New
A  0.586847 -1.621348  0.677535  0.026105  1.264382
B -1.678284  0.333973 -0.532471  2.117727 -2.210754
C  0.197524  2.302987  0.729024 -0.863091  0.926548
D  0.305632  0.243178  0.864165 -1.560931  1.169796
E -0.251897 -0.578120  0.236996  0.200780 -0.014901

In [49]:
df.drop("New",axis=1)

          W         X         Y         Z
A  0.586847 -1.621348  0.677535  0.026105
B -1.678284  0.333973 -0.532471  2.117727
C  0.197524  2.302987  0.729024 -0.863091
D  0.305632  0.243178  0.864165 -1.560931
E -0.251897 -0.578120  0.236996  0.200780

In [50]:
df

          W         X         Y         Z       New
A  0.586847 -1.621348  0.677535  0.026105  1.264382
B -1.678284  0.333973 -0.532471  2.117727 -2.210754
C  0.197524  2.302987  0.729024 -0.863091  0.926548
D  0.305632  0.243178  0.864165 -1.560931  1.169796
E -0.251897 -0.578120  0.236996  0.200780 -0.014901

In [51]:
df.drop("New",axis=1,inplace=True)

In [52]:
df

          W         X         Y         Z
A  0.586847 -1.621348  0.677535  0.026105
B -1.678284  0.333973 -0.532471  2.117727
C  0.197524  2.302987  0.729024 -0.863091
D  0.305632  0.243178  0.864165 -1.560931
E -0.251897 -0.578120  0.236996  0.200780

In [53]:
df.shape

(5, 4)

### Selecting rows

In [54]:
df

          W         X         Y         Z
A  0.586847 -1.621348  0.677535  0.026105
B -1.678284  0.333973 -0.532471  2.117727
C  0.197524  2.302987  0.729024 -0.863091
D  0.305632  0.243178  0.864165 -1.560931
E -0.251897 -0.578120  0.236996  0.200780

In [55]:
df.loc[["A","B"]]

          W         X         Y         Z
A  0.586847 -1.621348  0.677535  0.026105
B -1.678284  0.333973 -0.532471  2.117727

In [56]:
df.iloc[2]

W    0.197524
X    2.302987
Y    0.729024
Z   -0.863091
Name: C, dtype: float64

In [57]:
df

          W         X         Y         Z
A  0.586847 -1.621348  0.677535  0.026105
B -1.678284  0.333973 -0.532471  2.117727
C  0.197524  2.302987  0.729024 -0.863091
D  0.305632  0.243178  0.864165 -1.560931
E -0.251897 -0.578120  0.236996  0.200780

In [58]:
df.loc["C","Y"]

0.7290237321354455

In [59]:
df.loc[["A","B"],["Y","Z"]]

          Y         Z
A  0.677535  0.026105
B -0.532471  2.117727

### Conditional selection

In [60]:
df

          W         X         Y         Z
A  0.586847 -1.621348  0.677535  0.026105
B -1.678284  0.333973 -0.532471  2.117727
C  0.197524  2.302987  0.729024 -0.863091
D  0.305632  0.243178  0.864165 -1.560931
E -0.251897 -0.578120  0.236996  0.200780

In [61]:
df["W"]>0

A     True
B    False
C     True
D     True
E    False
Name: W, dtype: bool

In [62]:
df[df["W"]>0]

          W         X         Y         Z
A  0.586847 -1.621348  0.677535  0.026105
C  0.197524  2.302987  0.729024 -0.863091
D  0.305632  0.243178  0.864165 -1.560931

In [63]:
df[df["W"]>0][["Y","X"]]

          Y         X
A  0.677535 -1.621348
C  0.729024  2.302987
D  0.864165  0.243178

In [64]:
df

          W         X         Y         Z
A  0.586847 -1.621348  0.677535  0.026105
B -1.678284  0.333973 -0.532471  2.117727
C  0.197524  2.302987  0.729024 -0.863091
D  0.305632  0.243178  0.864165 -1.560931
E -0.251897 -0.578120  0.236996  0.200780

In [ ]:
df[(df["X"]>0) & (df["Z"]<0)][["X","Y"]]

          X         Y
C  2.302987  0.729024
D  0.243178  0.864165

In [66]:
df[(df["X"]>0) | (df["W"]<0)].reset_index()

  index         W         X         Y         Z
0     B -1.678284  0.333973 -0.532471  2.117727
1     C  0.197524  2.302987  0.729024 -0.863091
2     D  0.305632  0.243178  0.864165 -1.560931
3     E -0.251897 -0.578120  0.236996  0.200780

In [67]:
df.reset_index()

  index         W         X         Y         Z
0     A  0.586847 -1.621348  0.677535  0.026105
1     B -1.678284  0.333973 -0.532471  2.117727
2     C  0.197524  2.302987  0.729024 -0.863091
3     D  0.305632  0.243178  0.864165 -1.560931
4     E -0.251897 -0.578120  0.236996  0.200780

In [ ]:
# creating new column

In [68]:
newidx=("AZ GE RU IR TR").split()
newidx

['AZ', 'GE', 'RU', 'IR', 'TR']

In [69]:
df["Countries"]=newidx

In [70]:
df

          W         X         Y         Z Countries
A  0.586847 -1.621348  0.677535  0.026105        AZ
B -1.678284  0.333973 -0.532471  2.117727        GE
C  0.197524  2.302987  0.729024 -0.863091        RU
D  0.305632  0.243178  0.864165 -1.560931        IR
E -0.251897 -0.578120  0.236996  0.200780        TR

In [46]:
df.set_index("Countries")

                  W         X         Y         Z
Countries
AZ         0.302665  1.693723 -1.706086 -1.159119
GE        -0.134841  0.390528  0.166905  0.184502
RU         0.807706  0.072960  0.638787  0.329646
IR        -0.497104 -0.754070 -0.943406  0.484752
TR        -0.116773  1.901755  0.238127  1.996652

# Groupby

In [52]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [62]:
df = pd.DataFrame(data)
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

** Now you can use the .groupby() method to group rows together based off of a column name. For instance let's group based off of Company. This will create a DataFrameGroupBy object:**

In [64]:
df.groupby('Company')

You can save this object as a new variable:

In [63]:
by_comp = df.groupby("Company")["Sales"].mean()
by_comp

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

And then call aggregate methods off the object:

In [200]:
by_comp.std()

              Sales
Company
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [201]:
by_comp.min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [202]:
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [203]:
by_comp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [ ]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [204]:
by_comp.describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [205]:
by_comp.describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [149]:
by_comp.describe().transpose()[['GOOG']]

Company            GOOG
Sales count    2.000000
      mean   160.000000
      std     56.568542
      min    120.000000
      25%    140.000000
      50%    160.000000
      75%    180.000000
      max    200.000000